from tkinter import *
root=Tk()
root.geometry("900x360")
root.option_add("*Font","aerial 14 bold")
lblName=Label(root,text="Enetr Name: ")
lblName.place(relx=0.05,rely=0.05)
txtName=Entry(root)
txtName.place(relx=0.2,rely=0.05)
lblName=Label(root,text="Enetr Phone: ")
lblName.place(relx=0.05,rely=0.20)
txtName=Entry(root)
txtName.place(relx=0.2,rely=0.20)
btnSubmit=Button(root,text="Submit")
btnSubmit.place(relx=0.3,rely=0.30)
root.mainloop()